# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import (
    get_patrol_observations_from_patrols_df_and_combined_params as get_patrol_observations_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.io import (
    get_patrols_from_combined_params as get_patrols_from_combined_params,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import process_events_details as process_events_details
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_path_layer as create_path_layer
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.results import (
    view_state_from_layers as view_state_from_layers,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import explode as explode
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_apn.tasks import (
    add_fullscreen_to_map as add_fullscreen_to_map,
)
from ecoscope_workflows_ext_apn.tasks import add_lat_lon_to_gdf as add_lat_lon_to_gdf
from ecoscope_workflows_ext_apn.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_apn.tasks import (
    collect_optional_layers as collect_optional_layers,
)
from ecoscope_workflows_ext_apn.tasks import (
    create_patrol_endpoint_layers as create_patrol_endpoint_layers,
)
from ecoscope_workflows_ext_apn.tasks import ensure_dataframe as ensure_dataframe
from ecoscope_workflows_ext_apn.tasks import (
    extract_using_str_accessor as extract_using_str_accessor,
)
from ecoscope_workflows_ext_apn.tasks import fill_skipsentinel as fill_skipsentinel
from ecoscope_workflows_ext_apn.tasks import (
    generate_patrol_report as generate_patrol_report,
)
from ecoscope_workflows_ext_apn.tasks import (
    get_event_categories as get_event_categories,
)
from ecoscope_workflows_ext_apn.tasks import get_eventnotes as get_eventnotes
from ecoscope_workflows_ext_apn.tasks import get_patrol_info as get_patrol_info
from ecoscope_workflows_ext_apn.tasks import get_user_me as get_user_me
from ecoscope_workflows_ext_apn.tasks import (
    map_event_category_display as map_event_category_display,
)
from ecoscope_workflows_ext_apn.tasks import (
    prepare_patrol_report_context as prepare_patrol_report_context,
)
from ecoscope_workflows_ext_apn.tasks import to_list as to_list
from ecoscope_workflows_ext_custom.tasks.io import (
    download_event_attachments as download_event_attachments,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import (
    load_local_spatial_file as load_local_spatial_file,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    user_details = (
        task(get_user_me)
        .validate()
        .set_task_instance_id("user_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("user_details") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    locale = (
        task(set_locale)
        .validate()
        .set_task_instance_id("locale")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(locale_str="es_ES", **(params.get("locale") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    outing_id = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("outing_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("outing_id") or {}))
        .call()
    )

    get_template_path = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("get_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("get_template_path") or {}))
        .call()
    )

    events = (
        task(get_events)
        .validate()
        .set_task_instance_id("events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "serial_number",
                "event_details",
                "event_category",
                "geometry",
                "patrol_segments",
            ],
            event_types=[],
            include_details=True,
            raise_on_empty=False,
            include_updates=False,
            include_display_values=True,
            include_related_events=False,
            include_null_geometry=False,
            **(params.get("events") or {}),
        )
        .call()
    )

    convert_events_to_user_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_to_user_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_to_user_tz") or {}),
        )
        .call()
    )

    patrol_info_extraction = (
        task(extract_using_str_accessor)
        .validate()
        .set_task_instance_id("patrol_info_extraction")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_to_user_tz,
            column_name="event_details",
            key="numero_patrulla",
            value=outing_id,
            **(params.get("patrol_info_extraction") or {}),
        )
        .call()
    )

    explode_patrol_info = (
        task(explode)
        .validate()
        .set_task_instance_id("explode_patrol_info")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_info_extraction,
            column_name="patrol_segments",
            ignore_index=False,
            **(params.get("explode_patrol_info") or {}),
        )
        .call()
    )

    segment_ids = (
        task(to_list)
        .validate()
        .set_task_instance_id("segment_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=explode_patrol_info,
            column_name="patrol_segments",
            **(params.get("segment_ids") or {}),
        )
        .call()
    )

    patrol_and_events_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("patrol_and_events_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            patrol_types=[],
            event_types=[],
            sub_page_size=100,
            raise_on_empty=False,
            include_patrol_details=True,
            truncate_to_time_range=True,
            include_null_geometry=False,
            **(params.get("patrol_and_events_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        .validate()
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=patrol_and_events_params,
            **(params.get("prefetch_patrols") or {}),
        )
        .call()
    )

    patrol_observations = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=patrol_and_events_params,
            **(params.get("patrol_observations") or {}),
        )
        .call()
    )

    convert_patrols_to_user_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_observations,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrols_to_user_timezone") or {}),
        )
        .call()
    )

    patrol_events = (
        task(unpack_events_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=patrol_and_events_params,
            **(params.get("patrol_events") or {}),
        )
        .call()
    )

    convert_events_to_user_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_events,
            timezone=get_timezone,
            columns=["time", "patrol_start_time"],
            **(params.get("convert_events_to_user_timezone") or {}),
        )
        .call()
    )

    patrol_events_f = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("patrol_events_f")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_to_user_timezone,
            column="patrol_segment_id",
            values=segment_ids,
            **(params.get("patrol_events_f") or {}),
        )
        .call()
    )

    patrol_ids = (
        task(to_list)
        .validate()
        .set_task_instance_id("patrol_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_events_f,
            column_name="patrol_id",
            **(params.get("patrol_ids") or {}),
        )
        .call()
    )

    patrol_observations_f = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("patrol_observations_f")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_to_user_timezone,
            column="patrol_id",
            values=patrol_ids,
            **(params.get("patrol_observations_f") or {}),
        )
        .call()
    )

    patrol_relocations = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("patrol_relocations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=patrol_observations_f,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type__display",
                "patrol_serial_number",
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("patrol_relocations") or {}),
        )
        .call()
    )

    patrol_trajectory = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_trajectory")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=patrol_relocations, **(params.get("patrol_trajectory") or {})
        )
        .call()
    )

    trajectory_stats = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("trajectory_stats")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_trajectory,
            groupby_cols=["extra__patrol_serial_number"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Tipo de Transporte",
                    "aggregator": "unique",
                    "column": "extra__patrol_type__display",
                    "decimal_places": None,
                },
                {
                    "display_name": "Inicio",
                    "aggregator": "min",
                    "column": "extra__patrol_start_time",
                    "decimal_places": None,
                },
                {
                    "display_name": "Fin",
                    "aggregator": "max",
                    "column": "extra__patrol_end_time",
                    "decimal_places": None,
                },
                {
                    "display_name": "Distancia Total (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 2,
                },
                {
                    "display_name": "Horas Totales (hr)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 2,
                },
            ],
            **(params.get("trajectory_stats") or {}),
        )
        .call()
    )

    renamed_trajectory_stats = (
        task(map_columns)
        .validate()
        .set_task_instance_id("renamed_trajectory_stats")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajectory_stats,
            raise_if_not_found=True,
            rename_columns={"extra__patrol_serial_number": "ID de Patrulla"},
            retain_columns=None,
            drop_columns=None,
            **(params.get("renamed_trajectory_stats") or {}),
        )
        .call()
    )

    trajectory_stats_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("trajectory_stats_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=renamed_trajectory_stats,
            **(params.get("trajectory_stats_table") or {}),
        )
        .call()
    )

    trajectory_stats_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("trajectory_stats_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=trajectory_stats_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="trajectory_stats_table",
            **(params.get("trajectory_stats_table_html") or {}),
        )
        .call()
    )

    trajectory_stats_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("trajectory_stats_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Resumen de Patrullas",
            data=trajectory_stats_table_html,
            **(params.get("trajectory_stats_table_sv") or {}),
        )
        .call()
    )

    total_patrols = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_trajectory,
            column_name="extra__patrol_id",
            **(params.get("total_patrols") or {}),
        )
        .call()
    )

    total_patrols_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_patrols_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Nro. de Patrullajes realizadas",
            decimal_places=0,
            data=total_patrols,
            **(params.get("total_patrols_sv") or {}),
        )
        .call()
    )

    total_distance = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_trajectory,
            column_name="dist_meters",
            **(params.get("total_distance") or {}),
        )
        .call()
    )

    total_distance_km = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_distance_km")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="m",
            new_unit="km",
            value=total_distance,
            **(params.get("total_distance_km") or {}),
        )
        .call()
    )

    total_distance_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_distance_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Nro. de Kilómetros recorridos",
            decimal_places=2,
            data=total_distance_km,
            **(params.get("total_distance_sv") or {}),
        )
        .call()
    )

    events_ids = (
        task(to_list)
        .validate()
        .set_task_instance_id("events_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_events_f, column_name="id", **(params.get("events_ids") or {})
        )
        .call()
    )

    events_details = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("events_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_to_user_tz,
            column="id",
            values=events_ids,
            **(params.get("events_details") or {}),
        )
        .call()
    )

    processed_events_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("processed_events_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_details,
            client=er_client,
            map_to_titles=True,
            ordered=True,
            **(params.get("processed_events_details") or {}),
        )
        .call()
    )

    event_categories = (
        task(get_event_categories)
        .validate()
        .set_task_instance_id("event_categories")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("event_categories") or {}))
        .call()
    )

    mapped_events = (
        task(map_event_category_display)
        .validate()
        .set_task_instance_id("mapped_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            events_df=processed_events_details,
            categories_df=event_categories,
            **(params.get("mapped_events") or {}),
        )
        .call()
    )

    events_with_lat_lon = (
        task(add_lat_lon_to_gdf)
        .validate()
        .set_task_instance_id("events_with_lat_lon")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(event_gdf=mapped_events, **(params.get("events_with_lat_lon") or {}))
        .call()
    )

    patrol_info = (
        task(get_patrol_info)
        .validate()
        .set_task_instance_id("patrol_info")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=processed_events_details, **(params.get("patrol_info") or {}))
        .call()
    )

    event_notes = (
        task(get_eventnotes)
        .validate()
        .set_task_instance_id("event_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event=events_with_lat_lon,
            client=er_client,
            use_index_as_id=False,
            **(params.get("event_notes") or {}),
        )
        .call()
    )

    event_subset = (
        task(select_columns)
        .validate()
        .set_task_instance_id("event_subset")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_lat_lon,
            raise_on_missing=False,
            columns=["id", "serial_number", "event_type_display"],
            **(params.get("event_subset") or {}),
        )
        .call()
    )

    eventnotes_add_event_serial_no = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("eventnotes_add_event_serial_no")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=event_notes,
            right=event_subset,
            on=None,
            how="left",
            left_on="event",
            right_on="id",
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("eventnotes_add_event_serial_no") or {}),
        )
        .call()
    )

    safe_notes = (
        task(ensure_dataframe)
        .validate()
        .set_task_instance_id("safe_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(df=eventnotes_add_event_serial_no, **(params.get("safe_notes") or {}))
        .call()
    )

    event_notes_subset = (
        task(select_columns)
        .validate()
        .set_task_instance_id("event_notes_subset")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=safe_notes,
            raise_on_missing=False,
            columns=["serial_number", "text"],
            **(params.get("event_notes_subset") or {}),
        )
        .call()
    )

    events_and_notes = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("events_and_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=events_with_lat_lon,
            right=event_notes_subset,
            on="serial_number",
            how="left",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value="",
            **(params.get("events_and_notes") or {}),
        )
        .call()
    )

    safe_events_and_notes = (
        task(fill_skipsentinel)
        .validate()
        .set_task_instance_id("safe_events_and_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_and_notes,
            default=events_with_lat_lon,
            **(params.get("safe_events_and_notes") or {}),
        )
        .call()
    )

    report_context = (
        task(prepare_patrol_report_context)
        .validate()
        .set_task_instance_id("report_context")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=safe_events_and_notes,
            patrol_info=patrol_info,
            **(params.get("report_context") or {}),
        )
        .call()
    )

    spatial_features = (
        task(get_spatial_features)
        .validate()
        .set_task_instance_id("spatial_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("spatial_features") or {}))
        .call()
    )

    spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=spatial_features,
            tooltip_columns=[],
            **(params.get("spatial_features_layer") or {}),
        )
        .call()
    )

    local_spatial_file = (
        task(load_local_spatial_file)
        .validate()
        .set_task_instance_id("local_spatial_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("local_spatial_file") or {}))
        .call()
    )

    local_spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("local_spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=local_spatial_file,
            tooltip_columns=[],
            **(params.get("local_spatial_features_layer") or {}),
        )
        .call()
    )

    patrol_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("patrol_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=patrol_trajectory, **(params.get("patrol_colormap") or {}))
        .call()
    )

    patrol_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("patrol_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_legend_title") or {}))
        .call()
    )

    patrol_tracks_layer = (
        task(create_path_layer)
        .validate()
        .set_task_instance_id("patrol_tracks_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=patrol_colormap,
            legend={
                "title": patrol_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            **(params.get("patrol_tracks_layer") or {}),
        )
        .call()
    )

    patrol_endpoint_layers = (
        task(create_patrol_endpoint_layers)
        .validate()
        .set_task_instance_id("patrol_endpoint_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajectory=patrol_colormap, **(params.get("patrol_endpoint_layers") or {})
        )
        .call()
    )

    event_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("event_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=mapped_events, **(params.get("event_colormap") or {}))
        .call()
    )

    event_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("event_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("event_legend_title") or {}))
        .call()
    )

    event_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("event_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap,
            legend={
                "title": event_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            **(params.get("event_layer") or {}),
        )
        .call()
    )

    optional_geo_layers = (
        task(collect_optional_layers)
        .validate()
        .set_task_instance_id("optional_geo_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[
                spatial_features_layer,
                local_spatial_features_layer,
                patrol_tracks_layer,
                patrol_endpoint_layers,
                event_layer,
            ],
            **(params.get("optional_geo_layers") or {}),
        )
        .call()
    )

    patrol_event_view_state = (
        task(view_state_from_layers)
        .validate()
        .set_task_instance_id("patrol_event_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[patrol_tracks_layer, event_layer],
            max_zoom=20,
            **(params.get("patrol_event_view_state") or {}),
        )
        .call()
    )

    patrol_event_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("patrol_event_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=optional_geo_layers,
            tile_layers=base_maps,
            view_state=patrol_event_view_state,
            output_type="html",
            static=False,
            title=None,
            max_zoom=17,
            legend_style={"placement": "bottom-right"},
            **(params.get("patrol_event_map") or {}),
        )
        .call()
    )

    patrol_event_map_fullscreen = (
        task(add_fullscreen_to_map)
        .validate()
        .set_task_instance_id("patrol_event_map_fullscreen")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html=patrol_event_map, **(params.get("patrol_event_map_fullscreen") or {})
        )
        .call()
    )

    persist_patrol_map = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_patrol_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrol_event_map_fullscreen,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix=None,
            **(params.get("persist_patrol_map") or {}),
        )
        .call()
    )

    patrol_event_map_to_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("patrol_event_map_to_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=persist_patrol_map,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params.get("patrol_event_map_to_png") or {}),
        )
        .call()
    )

    patrol_event_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_event_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mapa de Patrulla y Eventos",
            data=persist_patrol_map,
            **(params.get("patrol_event_map_widget") or {}),
        )
        .call()
    )

    download_attachments = (
        task(download_event_attachments)
        .validate()
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            event_gdf=event_colormap,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            use_index_as_id=False,
            **(params.get("download_attachments") or {}),
        )
        .call()
    )

    norm_template_path = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(path=get_template_path, **(params.get("norm_template_path") or {}))
        .call()
    )

    norm_output_dir = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_output_dir")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("norm_output_dir") or {}),
        )
        .call()
    )

    generate_word_doc = (
        task(generate_patrol_report)
        .validate()
        .set_task_instance_id("generate_word_doc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            total_distance=total_distance_km,
            outing_id=outing_id,
            context=report_context,
            trajs=patrol_trajectory,
            trajs_stats=renamed_trajectory_stats,
            events=event_colormap,
            notes=[],
            user_details=user_details,
            attachments=download_attachments,
            template_path=norm_template_path,
            output_dir=norm_output_dir,
            mapa=patrol_event_map_to_png,
            **(params.get("generate_word_doc") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_patrols_sv,
                total_distance_sv,
                trajectory_stats_table_sv,
                patrol_event_map_widget,
            ],
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
